
stages:
  - pages
  - build
  - test
  - deploy

pages:
  stage: pages
  script:
  - mkdir .public
  - cp -r public/index.html .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master

build:
  stage: build
  image: python:3.6-slim
  artifacts:
    paths:
      - dist/
  script:
   - python setup.py sdist

test:
  stage: test
  image: python:3.6-slim
  dependencies:
    - build
  script:
    - pip install -e .
    - pytest

deploy_staging:
  stage: deploy
  image: python:3.6-slim
  variables:
    TWINE_USERNAME: $STAGING_USERNAME
    TWINE_PASSWORD: $STAGING_PASSWORD
  environment:
    name: staging
    url: $TESTPYPI_URL
  dependencies:
    - build
  only:
    - master
  except:
    - tags
  script:
    - pip install twine
    - twine upload --repository-url $TESTPYPI_URL dist/*

deploy_production:
  stage: deploy
  image: python:3.6-slim
  variables:
    TWINE_USERNAME: $PRODUCTION_USERNAME
    TWINE_PASSWORD: $PRODUCTION_PASSWORD
  environment:
    name: production
    url: https://pypi.org/project/statespace/
  dependencies:
    - build
  only:
    - tags
  except:
    - branches
  script:
    - pip install twine
    - twine upload dist/*

