image: python:3.6-slim

stages:
  - build
  - deploy

build:
  stage: build
  artifacts:
    paths:
      - dist/
  script:
   - python setup.py sdist

deploy_staging:
  stage: deploy
  variables:
    TWINE_USERNAME: $STAGING_USERNAME
    TWINE_PASSWORD: $STAGING_PASSWORD
  environment:
    name: staging
    url: $PYPRI_REPOSITORY_URL
  dependencies:
    - build
  only:
    - master
  except:
    - tags
  script:
    - pip install twine
    - twine upload --repository-url $PYPRI_REPOSITORY_URL dist/*

deploy_production:
  stage: deploy
  variables:
    TWINE_USERNAME: $PRODUCTION_USERNAME
    TWINE_PASSWORD: $PRODUCTION_PASSWORD
  environment:
    name: production
    url: https://pypi.org/project/statespace/
  dependencies:
    - build
  only:
    - tags
  except:
    - branches
  script:
    - pip install twine
    - twine upload dist/*
