#https://coderefinery.github.io/documentation/
name: docs
on: [push, pull_request, workflow_dispatch]
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: poetry
        uses: snok/install-poetry@v1
      - name: install
        run: poetry install --no-interaction --no-root
      - name: sphinx
        run: |
          sphinx-build docs docs/_build
          sphinx-build docs -W -b linkcheck -d docs/_build/doctrees docs/_build/html
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/
          force_orphan: true
