#https://coderefinery.github.io/documentation/
#https://tomasfarias: dev/posts/sphinx-docs-with-poetry-and-github-pages/:
name: docs
on:
  push:
    tags:
    - "v*.*.*"
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: pip install sphinx sphinx_rtd_theme
    - run: sphinx-build -a -E docs docs/_build
    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/
        force_orphan: true
