#https://github.com/JRubics/poetry-publish
name: pypi
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: publish to pypi
        uses: JRubics/poetry-publish@v1.15
        with:
          python_version: "3.10.8"
#          poetry_version: "==1.1.15" # (PIP version specifier syntax)
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          build_format: "sdist"
          allow_poetry_pre_release: "yes"
          ignore_dev_requirements: "yes"

