#https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
name: pypi
on:
  push:
    tags:
    - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: setup
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - name: pip install
      run: >-
        python3 -m
        pip install
        build
        --user
    - name: wheel and tarball
      run: python3 -m build
    - name: dist
      uses: actions/upload-artifact@v3
      with:
        name: python-package-distributions
        path: dist/
  pypi:
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/statespace
    permissions:
      id-token: write
    steps:
    - name: download
      uses: actions/download-artifact@v3
      with:
        name: python-package-distributions
        path: dist/
    - name: publish
      uses: pypa/gh-action-pypi-publish@release/v1
  github:
    needs:
    - pypi
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
    - name: download
      uses: actions/download-artifact@v3
      with:
        name: python-package-distributions
        path: dist/
    - name: sign
      uses: sigstore/gh-action-sigstore-python@v1.2.3
      with:
        inputs: >-
          ./dist/*.tar.gz
          ./dist/*.whl
    - name: release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: >-
        gh release create
        '${{ github.ref_name }}'
        --repo '${{ github.repository }}'
        --notes ""
    - name: upload
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: >-
        gh release upload
        '${{ github.ref_name }}' dist/**
        --repo '${{ github.repository }}'
